pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh '''
                    eval $(minikube docker-env)
                    docker build -t flask-app:latest ./app
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f ./k8s/deployment.yaml'
            }
        }
    }
}
